--[[
   Copyright © 2025 Davi PEIXELAS
   Licensed under the MIT License.
   See LICENSE file in the project root for full license text.
   
   GTA-SA BONES
    built and generated by: PEIXE
     | returns bone id by name |
   https://discord.gg/N49fmtT3VZ   -community
--]]
--     use require"BodyParts"
-- print(bonesById(5).name) or
-- print(bonesByName("Head").id) or
-- print(getBoneName(22)) or
-- print(getBoneId("LCalf")) or

local data = {
    [0]  = { id = 0,  name = "Root" },
    [1]  = { id = 1,  name = "Pelvis" },
    [2]  = { id = 2,  name = "Spine" },
    [3]  = { id = 3,  name = "Spine1" },
    [4]  = { id = 4,  name = "Neck" },
    [5]  = { id = 5,  name = "Head" },
    [6]  = { id = 6,  name = "LBrow" },
    [7]  = { id = 7,  name = "RBrow" },
    [8]  = { id = 8,  name = "Jaw"},
    [21] = { id = 21, name = "RClavicle" },
    [22] = { id = 22, name = "RUpperArm" },
    [23] = { id = 23, name = "RForearm" },
    [24] = { id = 24, name = "RHand" },
    [25] = { id = 25, name = "RFingers" },
    [26] = { id = 26, name = "RFinger01" },
    [31] = { id = 31, name = "LClavicle" },
    [32] = { id = 32, name = "LUpperArm"},
    [33] = { id = 33, name = "LForearm" },
    [34] = { id = 34, name = "LHand" },
    [35] = { id = 35, name = "LFingers" },
    [36] = { id = 36, name = "LFinger01" },
    [41] = { id = 41, name = "LThigh" },
    [42] = { id = 42, name = "LCalf" },
    [43] = { id = 43, name = "LFoot" },
    [44] = { id = 44, name = "LToe"},
    [51] = { id = 51, name = "RThigh" },
    [52] = { id = 52, name = "RCalf" },
    [53] = { id = 53, name = "RFoot" },
    [54] = { id = 54, name = "RToe" },
    [201] = { id = 201, name = "Belly" },
    [301] = { id = 301, name = "RBreast" },
    [302] = { id = 302, name = "LBreast" },
}

bonesById = setmetatable({},{
    __call = function(__, id)
        return data[id]
    end
})
bonesByName = setmetatable({},{
    __call = function(__, name)
        for __, bone in pairs(data) do
            if bone.name == name then
                return bone
            end
        end
        return nil
    end
})

getBoneName = function(id)
    local bone = data[id]
    return bone and bone.name or nil
end

getBoneId = function(name)
    for __, bone in pairs(data) do
        if bone.name == name then
            return bone.id
        end
    end
    return nil
end

